### ISSUE TITLE
How to read Zbraln data？

### ISSUE THREAD

**Issue by yangsenwxy** [Zero-We/PMIL#1]
Hi,
Thank you very much for your work, what software can you use to read Zbraln data? openslide doesn't seem to be able to read Zbraln data, can you share more data？

**Comment by zihou98** [comment]
Hi,  
[#270](https://github.com/openslide/openslide/pull/270) was submitted to add dmetrix slide format, but which has not been merged into openslide yet. You could recompile openslide to read dmetrix slides on Zbraln.  We are sorry about that we can not share more slide data because of the privacy policy. And I have uploaded the software that reads Zbraln data to Baidu Cloud and Google Drive.
